### ISSUE TITLE
Fedora 34 extension does not work

### ISSUE THREAD

**Issue by IvanDeFelice76** [HarlemSquirrel/gnome-shell-extension-sensory-perception#38] opened 2021-06-16 15:27 UTC
GLib.ShellError: Il testo era vuoto (oppure conteneva unicamente spazi bianchi)

Stack trace:
  _getSensorsLabels@/home/X555LP/.local/share/gnome-shell/extensions/sensory-perception@HarlemSquirrel.github.io/prefs.js:205:40
  _init@/home/X555LP/.local/share/gnome-shell/extensions/sensory-perception@HarlemSquirrel.github.io/prefs.js:154:14
  buildPrefsWidget@/home/X555LP/.local/share/gnome-shell/extensions/sensory-perception@HarlemSquirrel.github.io/prefs.js:286:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by HarlemSquirrel** [comment] 2021-06-19 14:32
Duplicate of #35

**Closed as completed by HarlemSquirrel** 2021-06-19 14:32 UTC
Labels: bug
